SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL';

CREATE  TABLE IF NOT EXISTS `timesheet` (
		`id` INT(11) NOT NULL AUTO_INCREMENT ,
		`title` VARCHAR(255) NULL DEFAULT NULL ,
		`date` DATE NULL DEFAULT NULL ,
		`start` VARCHAR(20) NULL DEFAULT NULL ,
		`end` VARCHAR(20) NULL DEFAULT NULL ,
		`minutes` DECIMAL(8,2) NULL DEFAULT NULL ,
		`notes` TEXT NULL DEFAULT NULL ,
		`url` VARCHAR(255) NULL DEFAULT NULL ,
		`calendar` VARCHAR(255) NULL DEFAULT NULL ,
		`report_id` INT(11) NULL DEFAULT NULL ,
	PRIMARY KEY (`id`) ,
	INDEX `fk_timesheet_report1` (`report_id` ASC) ,
	CONSTRAINT `fk_timesheet_report1`
	FOREIGN KEY (`report_id` )
	REFERENCES `report` (`id` )
	ON DELETE NO ACTION
	ON UPDATE NO ACTION)
ENGINE = InnoDB
CHARACTER SET = utf8 , COLLATE = utf8_general_ci;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

