SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL';

ALTER TABLE `task` ADD COLUMN `status` VARCHAR(20) NULL DEFAULT NULL  AFTER `name` , ADD COLUMN `project_id` INT(11) NULL DEFAULT NULL  AFTER `budget_id` , CHANGE COLUMN `screen_id` `screen_id` INT(11) NULL DEFAULT NULL  AFTER `cur_progress` , 
  ADD CONSTRAINT `fk_task_project1`
  FOREIGN KEY (`project_id` )
  REFERENCES `project` (`id` )
  ON DELETE NO ACTION
  ON UPDATE NO ACTION
, ADD INDEX `fk_task_project1` (`project_id` ASC) ;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
