SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL';

ALTER TABLE `timesheet`  ADD COLUMN `user_id` INT(11) NULL DEFAULT NULL  AFTER `report_id` 
, ADD INDEX `fk_timesheet_user1` (`user_id` ASC) ;

ALTER TABLE `user` ADD COLUMN `hash` VARCHAR(255) NULL DEFAULT NULL  AFTER `is_developer` ;

update user set hash=md5(rand());

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

