SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL';

ALTER TABLE `budget` ADD COLUMN `project_id` INT(11) NOT NULL  AFTER `accepted` , 
  ADD CONSTRAINT `fk_budget_project1`
  FOREIGN KEY (`project_id` )
  REFERENCES `project` (`id` )
  ON DELETE NO ACTION
  ON UPDATE NO ACTION
, ADD INDEX `fk_budget_project1` (`project_id` ASC) ;

ALTER TABLE `task` DROP FOREIGN KEY `fk_task_budget1` ;

ALTER TABLE `task` 
  ADD CONSTRAINT `fk_task_budget1`
  FOREIGN KEY (`budget_id` )
  REFERENCES `budget` (`id` )
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

